### ISSUE TITLE
Zawór 4D zmiana kierunku - dodatkowy czas

### ISSUE THREAD

**Issue by mecenas8** [uzi18/sterownik#104]
Witam

Posiadany przeze mnie zawór 4D posiada pewien martwy czas po zmianie kierunku otwieranie/zamykanie, lub zamykanie/otwieranie. Siłownik pracuje, jednak nie porusza zaworu. Ten luz wynika z budowy mojego zaworu.

Czy istniałaby możliwość wstawienia w kod zaworu wydłużania czasu ruchu zaworu po zmianie kierunku, w celu skasowania luzu?

Coś w rodzaju:

if (kierunek_zaworu != kierunek_zaworu_old)  czas_zaworu+= DODATKOWY_CZAS_ZAWORU;
kierunek_zaworu_old = kierunek_zaworu;

**Comment by uzi18** [comment]
jak dlugi to okres? Moze przy zmianie kierunku nie ma sensu dzielenie kroku na mniejsze czesci?
wklej reszte parametrow konfiguracji zaworu

**Comment by mecenas8** [comment]
4s krok, 240s pelny ruch, 50s czas regulacji, martwy ruch to mysle ze ok 10-15s.

**Comment by mecenas8** [comment]
ZAWOR4D-CZAS_OTWARCIA = 240
ZAWOR4D-CZAS_KROK = 4
ZAWOR4D-CZAS_POMIARU = 50

**Comment by uzi18** [comment]
nadal potrzebne?

**Comment by mecenas8** [comment]
Przydałoby się

**Comment by uzi18** [comment]
@mecenas8 dodane w zalaczonej wersji zapraszam do testow :)
```
#martwy czas dla zmiany kierunku (10 = 1s.)
ZAWOR4D-CZAS_ZMIANY_KIERUNKU=0
```
[Lucjan.hex_33p.zip](https://github.com/uzi18/sterownik/files/4441221/Lucjan.hex_33p.zip)

**Comment by uzi18** [comment]
@mecenas8 zakladam ze dziala
