### ISSUE TITLE
Nettemp- po restarcie maliny nie działaja czujniki. 

### ISSUE THREAD

**Issue by swiezaks** [uzi18/sterownik#114]
Cześć. Mam drugą malinę i na niej NT. wszystko poinstalowane bez problemów, lucjan posyła dane do NT, po zrestartowaniu maliny dane z czujników nie docierają do NT, jak ręcznie uruchomię test.py to wszystko znowu działa do czasu kolejnego restartu maliny. Uprawnienia dla plików mam 0777. na końcu pliku rclocal mam exit0 tak jak w instrukcji pisze. 
![lucjan](https://user-images.githubusercontent.com/31879697/120118270-e3ba7b00-c191-11eb-905c-4e6d89b72b1a.jpg)
![rclocal](https://user-images.githubusercontent.com/31879697/120118271-e61cd500-c191-11eb-89db-f75d5ef9b92a.jpg)

**Comment by uzi18** [comment]
@swiezaks 
zaloguj sie przez putty lub uruchom terminal i wpisz: 
screen -r

wklej mi komunikaty

**Comment by swiezaks** [comment]
root@pi4:/home/pi# cd /home/pi/lucjan/
root@pi4:/home/pi/lucjan# screen -r
There is no screen to be resumed.

![lucek1](https://user-images.githubusercontent.com/31879697/128868559-ebe603bc-b81b-46d8-aa27-0c1abacde3d6.jpg)

**Comment by uzi18** [comment]
Cos sie zmienilo w nettemp?

**Comment by swiezaks** [comment]
Nic się nie zmieniło, aktualizacji juz dawno nie było;) jak ręcznie uruchomię skrypt to wszystko działa do czasu aż zrestartuję malinę, czyli na mój gust jest problem z autostartem "screen".

**Comment by uzi18** [comment]
Z logu wynika ze czesc danych sie zapisuje do bazy a czesc nie bo nie widzi baz a za to odpowiada nettemp.
Nie ma w nim nowych urzadzen wykrytych?

**Comment by swiezaks** [comment]
docelowo stara malina zostanie wyłączona i na jednej nowej wszystko będzie działało. teraz na czas testów mam dodane kilka czujników ale nie wszystkie. W wolnej chwili jak mi się jeszcze dzisiaj zdalnie z pracy uda to dodam wszystkie czujniki, może to jest problemem?

**Comment by swiezaks** [comment]
dodałem wszystkie czujniki ale to nadal nie to, po restarcie maliny o ile dobrze rozumiem nie uruchamia się z automatu test.py w katalogu /run/screen/S-pi/ nie mam żadnego pliku tak jak jest to na drugiej malinie.
Na gitterze w PW podesłałem informacje,

**Comment by uzi18** [comment]
```
root@pi4:/home/pi# chown -Rv pi:pi lucjan
właściciel 'lucjan/konfiguracja.py' zachowany jako pi:pi
właściciel 'lucjan/test.py.log' zmieniony z root:root na pi:pi
właściciel 'lucjan/test.py' zachowany jako pi:pi
właściciel 'lucjan/konfiguracja.pyc' zmieniony z root:root na pi:pi
właściciel 'lucjan' zachowany jako pi:pi

```

**Comment by uzi18** [comment]
skopiowales z prawami root dlatego nie dzialalo

**Comment by swiezaks** [comment]
dziękuję bardzo za pomoc:) wszystko śmiga
