### ISSUE TITLE
parametry bezpieczenstwa pracy pieca

### ISSUE THREAD

**Issue by uzi18** [uzi18/sterownik#12]
TMAX = 80 -> wylaczenie dmuchawy i uruchomienie pompek.
TMIN = 30 -> tylko alarm?

PODAJNIK_TEMP_MAX = 60
PODAJNIK_CZAS_WYRZUTU=5
-> 60 stopni podajnika -> wyrzut przez 5min.

cos jeszcze?

Potrzebne do algorytmu retortowy-reczny

**Comment by mark3k3** [comment]
Dla instalacji z zaworem N-drożnym i siłownikiem elektrycznym, po przekroczeniu TMAX wydanie polecenia max otwarcia zaworu.

**Comment by uzi18** [comment]
Zabezpieczenie przed wysoka temperatura podajnika i pieca dodane, dodatkowo obsluga zaworu 4D ma dodane otwieranie zaworu w przypadku przegrzania pieca zgodnie z sugestia mark3k3.
