### ISSUE TITLE
WWW: dodac logowanie na haslo

### ISSUE THREAD

**Issue by bzykbzyk** [uzi18/sterownik#20]
Dodać zabezpieczenie strony

**Comment by bzykbzyk** [comment]
Zabezpieczenie strony

**Comment by uzi18** [comment]
Jestem w trakcie dopisywania tej funkcji. 
@Stan17 @mipurel @mark3k3 @ravikjab dodam na poczatek podstawowe hasla a pozniej mozliwosc zdefiniowania swojego loginu i hasła.
Macie jakies pomysly w tym temacie?
Domyslnie wlaczyc to zabezpieczenie? 
API www tez zablokowac hasłem?

**Comment by mipurel** [comment]
W API na pewno należy zabezpieczyć funkcje nieinformacyjne czyli dać na hasło np. reset, set,  modulacje i configreload. Większość użytkowników nie ma potrzeby zabezpieczania dlatego sądzę, że domyślnie można zostawić wyłączone. W moim przypadku chciałbym, żeby wszyscy mieli podgląd do www (bez config.txt) a podgląd i zmiana była możliwa tylko przez osobę uprawnioną.

**Comment by uzi18** [comment]
dodano w 0.1.0.129.4
