### ISSUE TITLE
Uwagi do WWW

### ISSUE THREAD

**Issue by bzykbzyk** [uzi18/sterownik#26]
"Predkosc podawania" - dobrze by było, gdyby była dostępna jako zmienna w config. Nie trzeba będzie wprowadzać po aktualizacji programu.

**Comment by Stan17** [comment]
Co do prędkości podawania to racja, wpisuje się to dość rzadko więc config jest na to dobrym miejscem.

Przydałby się timer odliczający od zadanej ilości węgla w zasobniku do zera (w przyszłości osiągnięcie zera , albo jakieś ustalonej wartości przed zerem generowałoby alarm).
I tutaj wielkość zasypu pożądana byłaby na stronie.

**Comment by uzi18** [comment]
dodane w 0.1.0.40, zapraszam do testow
