### ISSUE TITLE
Dmuchawa AC - jak wygląda rozruch?

### ISSUE THREAD

**Issue by bzykbzyk** [uzi18/sterownik#29]
Jak wygląda sekwencja sterowania dmuchawą? Czy jest i jak długo trwa impuls rozruchu?

**Comment by uzi18** [comment]
Zerknij na zmienne DM_ROZRUCH_CZAS i DM_ROZRUCH_MOC

2016-04-17 8:53 GMT+02:00 bzykbzyk <notifications@github.com>:

**Comment by bzykbzyk** [comment]
Widziałem te zmienne, ale sądziłem że odnoszą się do modulacji. Mają zastosowanie również bez modulacji?

**Comment by uzi18** [comment]
Te tak.
