### ISSUE TITLE
RR: problem z histereza przy paleniu

### ISSUE THREAD

**Issue by uzi18** [uzi18/sterownik#35]
Zauważyłem chyba błąd w sterowaniu gdyż przy ustawieniu TPIECA na 50 st i histereza na 2 st. to przy spadaniu temp podajnik właczył się przy 47,9 st (czyli prawidłowo), natomiast gdy temp rosła to już po przekroczeniu 48 st podajnik przestał się właczać a powinien pracować do uzyskania nastawionej temperatury 50 st.

**Comment by uzi18** [comment]
faktycznie to jest do poprawki

**Comment by uzi18** [comment]
poprawione w #d73161670b15a94e1a202113f096e97f53496d42

**Comment by ravikjab** [comment]
nie wyłącza się podajnik i dmuchawa pomimo przekroczenia ustawionej tPIEC.

**Comment by uzi18** [comment]
wklej tutaj swoj config.txt

**Comment by uzi18** [comment]
naprawione w v.0.1.0.47
