### ISSUE TITLE
Buzer awarii

### ISSUE THREAD

**Issue by ravikjab** [uzi18/sterownik#39]
Należy dodać zewnętrzny buzer do alarmów przekroczonej tPODAJNK, pustego zbiornika, uszkodzonego któregoś czujnika oraz awarii napędu podajnika. Różne częstotliwości dla różnych awarii by bez logowania szybko móc zlokalizować awarie

**Comment by ravikjab** [comment]
Dodać wyjście na buzer podczas awarii.

**Comment by uzi18** [comment]
dodane w wersji v0.1.0.65
podpinamy pod pin 31 - Low Level Trigger Buzzer Module
