### ISSUE TITLE
DM: dopalanie nie dziala w trybie RRM

### ISSUE THREAD

**Issue by ravikjab** [uzi18/sterownik#48]

**Comment by uzi18** [comment]
podczas pracy dopalania tlo nie moze dzialac

**Comment by uzi18** [comment]
v0.1.0.107
    - dokończenie nowego dopalania - gotowe do testów
    - w trakcie pracy tła przekroczenie zadana+max_przebicie wyłącza tło całkowicie
    - tło i dopalanie nie mogą być włączone jednocześnie

**Comment by uzi18** [comment]
Ponizej nowe opcje, działają tylko jesli ustawiono PIEC_ALGORYTM = RRM2

2 - wlaczone dopalanie, 1 - wlaczone tlo, 0 -wylaczone tlo i dopalanie
RRM_TLO_WLACZONE=0
# dopalanie 150s 30%
RRM_DOPALANIE_MOC=30
RRM_DOPALANIE_CZAS=150
