### ISSUE TITLE
lista standardowych czujnikow

### ISSUE THREAD

**Issue by uzi18** [uzi18/sterownik#5]
Pelna lista:
CO
CWU
POWROT
ZEW
KOMIN
PIEC
PODAJNIK
PODLOG
T1-T8 (uniwersalne)

**Comment by bzykbzyk** [comment]
ZEW
KOMIN
PIEC
CWU1
PODAJNIK
PODLOG

**Comment by uzi18** [comment]
CWU1 czy CWU2 ?

**Comment by uzi18** [comment]
Czym sie rozni CO od PIEC?

**Comment by whitemar** [comment]
Witam Was,
Proponowałbym powielić czujnik CO, jako zabezpieczenie w razie jego uszkodzenia: CO1 i CO2. Pełniłyby tę samą funkcję i były ulokowane w tym samym miejscu, a awaria jednego z nich (zbyt duża różnica wskazań CO1 i CO2) wymuszałaby alarm o konieczności wymiany. Drugi czujnik w tym czasie zapobiegłby unieruchomieniu kotła.

**Comment by bzykbzyk** [comment]
CO to temperatura wody za czterodrogowym (jeśli jest) albo na rurociągu "zasilanie" a PIEC to bezpośrednio w pochwie pieca. 
Nie trzeba powielania (każdy czujnik może ulec uszkodzeniu, trzeba by wszystkie powielać). Niebezpieczny jest niekontrolowany wzrost temp pieca. Oprócz czujników konieczne zastosowanie termostatów (jak na schemacie): bezpośrednio w pochwie 90-95st odcinający zasilanie dmuchawy i podajnika - piec zgłosi awarię brak paliwa, albo dwóch nc i no - jeden rozłączy zasilanie, drugi wyśle sygnał do sterownika, albo jednego z przekaźnikiem przełączającym.

**Comment by uzi18** [comment]
Podoba mi sie ta opcja ... PIEC na piecu a obwody jako CO1,CO2 itp.

**Comment by bzykbzyk** [comment]
Jeśli czujnikom dodatkowym można nadać nazwy, to oczywiście PODLOG i KOMIN wyrzuć z podstawowych, no chyba że dodatkowe to tylko DS.

**Comment by uzi18** [comment]
bzyk nie ma/nie bedzie ograniczen w tej kwestii po to bedzie wlasnie mapowanie :)

**Comment by uzi18** [comment]
aktualnie zrobilem takie:
  t_piec,
  t_powrot,
  t_podajnik,
  t_zew,
  t_cwu,
  t_spaliny,
  t_t1,
  t_t2,
  t_t3,
  t_t4,
  t_t5,
  t_t6,
  t_t7,
  t_t8

**Comment by bzykbzyk** [comment]
No bo już zaczęły pleśnieć mi płytki a synek już czaił się żeby je spożytkować....

**Comment by uzi18** [comment]
Bez przesady moja 2 maluchow tez absorbuja, a najchetniej by sie tym wszystkim bawili :)
