### ISSUE TITLE
Aktualny czas na wyświetlaczu

### ISSUE THREAD

**Issue by Stan17** [uzi18/sterownik#52]
Stary temat z ES i niemożliwy tam do zaimplementowania w starych sterownikach.

**Comment by uzi18** [comment]
Godzina i minuta?

**Comment by Stan17** [comment]
No tak, więcej nie potrzeba.

**Comment by uzi18** [comment]
Bedzie w lewym gornym rogu na 16x2

**Comment by uzi18** [comment]
dodane w v0.1.0.75

**Comment by bzykbzyk** [comment]
może jeszcze synchronizacja z ntp?

**Comment by uzi18** [comment]
Jest przy uruchomieniu.

**Comment by bzykbzyk** [comment]
może jeszcze data?

**Comment by uzi18** [comment]
Jak chcesz jakas funkcje to zaloz nowy issue, a nie wszystko do jednego worka.
Druga sprawa nie da sie wszystkiego na lcd wrzucic na raz.
Temat jest zamkniety
