### ISSUE TITLE
Ustawienie czasu podawania z LCD

### ISSUE THREAD

**Issue by wwpiotr** [uzi18/sterownik#55]
Dodać możliwość zmiany czasu podawania z poziomu LCD, dodatkowo można dodać możliwość zmiany prędkości dmuchawy.

**Comment by uzi18** [comment]
Praca i podtrzymanie?

**Comment by wwpiotr** [comment]
Wystarczy praca

Wysłane z iPhone'a

Dnia 25.01.2017 o godz. 16:18 Bartłomiej Zimoń <notifications@github.com> napisał(a):

**Comment by uzi18** [comment]
dodane dla algorytmow RR,RRM i ZASYPOWY
