### ISSUE TITLE
Poprawienie działania "tła"

### ISSUE THREAD

**Issue by Stan17** [uzi18/sterownik#57]
Dodanie do tła dawek paliwa.
W dalszej kolejności musimy przemyśleć automatyzację działania tła, np w trybie LATO nie ma ono sensu.

**Comment by uzi18** [comment]
podczas pracy tla dopalanie nie powinno dzialac

**Comment by Stan17** [comment]
Dokładnie, tak samo podtrzymanie.

**Comment by uzi18** [comment]
Ponizej nowe opcje, działają tylko jesli ustawiono PIEC_ALGORYTM = RRM2

# 1 - wlaczone tlo, 0 -wylaczone tlo
RRM_TLO_WLACZONE=0
RRM_TLO_MOC=20
RRM_TLO_CZAS_PODANIE=10
# w min.
RRM_TLO_CZAS=15

**Comment by uzi18** [comment]
w wersji v0.1.0.106 dodano zabezpieczenie przed nadmiernym wzrostem temperatury i przechodzimy wtedy w podtrzymanie
nowa opcja :

#jesli tlo podbije TPIEC 5deg ponad zadana przechodzimy w podtrzymanie
RRM_MAX_PRZEBICIE_TLO=5

**Comment by uzi18** [comment]
v0.1.0.107
    - dokończenie nowego dopalania - gotowe do testów
    - w trakcie pracy tła przekroczenie zadana+max_przebicie wyłącza tło całkowicie
    - tło i dopalanie nie mogą być włączone jednocześnie
