### ISSUE TITLE
sterowanie 2 okładami centralnego ogrzewania. 

### ISSUE THREAD

**Issue by sargus123** [uzi18/sterownik#78]
Mam instalację rozbudowaną na kilka stref centralnego ogrzewania. jedna pompa chodzi cały rok a inne są włączane gdy temperatura spadnie poniżej  13 stopni. 

może dopisać warunek  z ustawieniem w configu. 
 jeśli tZEW jest poniżej [ ...] to  załącz pompę [ podajemy jaką ]

**Comment by uzi18** [comment]
ta pompa pracujaca caly rok to pompa CO? Moze warto dodac pompe mieszajaca, 
pod ktora moglbys ja podlaczyc a tamta 2ga wpiac jako CO w trybie AUTOLATO

**Comment by sargus123** [comment]
Tak pierwsza pompa to pompa transmisyjna tłoczy wodę w głównej magistrali. do bojlera (przelotowo bezpośrednio przelatuje), budynku A,B,C i do bojlera głównego w budynku C
Do niej są podłączone budynki poprzez wymienniki płytowe gdzie w takim połączeniu musi być  pompa.  (mieszacza nie mogę podłączyć różnica ciśnień i część układu przechodzi w tryb chłodzenia /coś ala woda lodowa/  mieszacz jest w części budynku A 

Wiem że nie obsłuży mi wszystkiego Lucjan z powodu odległości. a magistrale mam tylko internetową.

**Comment by uzi18** [comment]
Jesli siec masz wspolna w budynkach to posrednio da sie to ugryzc.

**Comment by sargus123** [comment]
tak mam sieć wspólną w budynkach.  :)

**Comment by uzi18** [comment]
Jesli jest to wszystko da sie zrobic

**Comment by sargus123** [comment]
to jestem gotów na propozycje  :) i z pewnością nie jednemu się przyda. kto ma instalację rozproszoną.
jeśli chodzi o obsłużenie wszystkich elektro zaworów, pomp, i zaworów 3 drożnych. Pomijając awaryjną linię zasilania w postaci pieca gazowego co przejmuję kontrolę grzania jak padnie piec na groszek. 
muszę znaleźć program do rysowania projektów kotłowni by rozpisać wizualnie instalację wtedy można zobaczyć jak to razem można sprzężyc we wspólne działanie.

**Comment by uzi18** [comment]
Do wszystkich prawie informacji jest dostep przez api www/serial,  wystarczy z nich skorzystac.
Np.  Wrzucic  je sobie do domoticz i nim przekazac dalej do espeasy czy czegokolwiek.

**Comment by uzi18** [comment]
Wystarczy Ci pompa cwu cyrkulacji jako podstawowy obwod czy musze dodac nowa do mieszania?

**Comment by uzi18** [comment]
update??
