### ISSUE TITLE
dmuchawa AC - moduły

### ISSUE THREAD

**Issue by uzi18** [uzi18/sterownik#8]
dmuchawa AC sterowana moze byc poprzez optotriak i triak - wymagany jest tez detektor zera sieci
lub
zmodyfikowany modul avt-1613 (dostepny w sprzedazy) z wyjscia PWM
lub 
modul avt-3113 (niedostepny w sprzedazy) z wyjscia PWM

**Comment by bzykbzyk** [comment]
uzi18, jesteś pewny że avt-3113 nadaje się do sterowania silników asynchronicznych? Producent twierdzi, że przeznaczony jest do komutatorowych.

**Comment by uzi18** [comment]
jestem pewny, w tym tygodniu przyjda płytki to zloze i sprawdze ale to jest praktycznie to samo co Stan zmontowal z 1613 i fragmentu z 3113 wiec nie ma innej mozliwosci

**Comment by uzi18** [comment]
Podsumowując moje testy: 
avt3113 - działa poprawnie : sygnał 0V-0% 5V-100%, mozliwosc regulacji minimalnych i maksymalnych obrotów oraz biegu jałowego, przy 100% obroty troszke pływają wiec warto zjechac troszke z obrotów maksymalnych potencjometrem na module

avt1613-zmodyfikowany wg Stan - działa poprawnie poza tym ze wymaga odwroconego sygnału (5V-0% 0V-100%) i u mnie na 0% dmuchawa sie nie potrafi zatrzymać.

triak-optotriak+detekcja zera - w trakcie testów

**Comment by bzykbzyk** [comment]
avt3113 niestety niedostępny

**Comment by uzi18** [comment]
Aktualizacja:

avt1613-zmodyfikowany wg Stan - działa poprawnie, 
wg. mnie kiepskie mozliwosci regulacji wzgledem 3113, prawdopodobnie mozna to jeszcze dopracowac
wczesniej zle dzialala bo u2008b mialem w podstawce,  najlepiej przylutowac go bezposrednio do plytki

avt3113- jest niedostepna i producent nie ma zamiaru jej wznowic do sprzedazy

**Comment by mark3k3** [comment]
Ogólnie, moduł AVT1613 działa dość poprawnie, jednak PWM nie może wysterować wentylatorem na MAX. MAX obroty nie są nam potrzebne, dlatego takie wykonanie modułu wykonawczego sterowania dmuchawą jest jak najbardziej akceptowalne i przydatne.

**Comment by bzykbzyk** [comment]
Dla dmuchawy nie jest potrzebne 100%, ale już np dla pompy tak.
Chciałbym w przyszłości wykorzystać Lucjana również do sterowania panelami słonecznymi i obrotami pompy: w zależności od różnicy temperatur przed i za panelami. Muszę zbudować układ na wzór avt3113, skoro lepiej steruje.

**Comment by uzi18** [comment]
Moze dla pompy zakres regulacji na avt1613 tez wystarcza.

W dniu 1 października 2016 19:43 użytkownik bzykbzyk <
notifications@github.com> napisał:

**Comment by bzykbzyk** [comment]
Muszę zatem zbudować jakieś stanowisko do pomiaru obrotów pompy i sprawdzić jak się zachowuje. Nawet jak by nie było max 100%, można w ostateczności zewrzeć regulator stykiem przekaźnika.

**Comment by uzi18** [comment]
Mozna ustawic/wyregulowac plytke 1613 aby byl zakres od 40%-100%.

**Comment by uzi18** [comment]
Moge potwierdzic ze swojej strony ze dmuchawka AC sterowana 
bezposrednio z Lucjana w  konfiguracji - detektor zera, optotriak, triak - smiga az milo ...

**Comment by bzykbzyk** [comment]
Mój piec na razie w gotowości do palenia. Przestawiam trochę szpeje w kotłowni więc brak czasu. Czekam na moduł triaków.
Skoro 1679 działa zadowalająco (w całym zakresie obrotów?) to rezygnujemy z 1613?
Dlaczego sterujesz triakami z wyjść analogowych a nie cyfrowych (dmuchawa - wiadomo)?
Uaktualniłem schemat (bez przekaźników na razie, info w wątku o przekaźnikach).

**Comment by uzi18** [comment]
Jezcze troche i zrobimy porzadki z wyjsciami.
Wyjscie na opto to jakiekolwiek zwykle wyjscie cyfrowe.

Czekam na wasze testy z moc3020, na razie nikt nie potwierdzil poprawnej
pracy, a 1613/3113 jest dobra alternatywa.

**Comment by bzykbzyk** [comment]
Przy porządkowaniu wyjść, rozpatrz przeniesienie gdzieś sygnałów DO i CLK termopary, dla triaków "cyfrowych" można by przeznaczyć wyjścia 46 -55 - zrobić kabelek 10 żyłowy (wtyk - gniazdo) kanda -  pewnie i prosto podpiąć moduł triaków (nie przerabiany) do mega jedną taśmą. W tej chwili wykorzystujemy już 8 wyjść do sterowań, lada chwila trzeba dołożyć kolejny moduł triaków. Jakaś pompa np do solarów też ładnie by hulała ze zmienną prędkością zależną od temp.

**Comment by ravikjab** [comment]
uruchomiłem dmuchawę na MOC3020 i po wstępnych testach praca dmuchawy WPA01 jest wielce obiecująca. Jest większa moc względem AV1613. Dmuchawa w trybie modulacji bez problemów zmienia predkość. 
Więcej informacji przekaże po dłuższych testach.

**Comment by uzi18** [comment]
ktoś jeszcze testował?

**Comment by uzi18** [comment]
v0.1.0.66
        - sterowanie triakiem dmuchawy (A13) zdublowane na pin 32

Docelowo będziemy musieli przenieść się z pinów Ax (zwłaszcza dmuchawa)z prostej przyczyny - procesor ma jakiś bug powodujący zakłócenia na wyjściach przełączanych z "wysoką" częstotliwością.

Tym samym czekam na potwierdzenie ze dmuchawa sterowana optotriak/triak działa już
poprawnie po podłączeniu pod pin 32.
A13 z czasem ... będzie to testów czujników np. KTY81-210.

**Comment by mark-markowski** [comment]
Potwierdzam prawidłowe działanie dmuchawy na pinie nr. 32. Modulacja działa płynnie i precyzyjnie.

**Comment by uzi18** [comment]
Rozumiem,że działa więc zamykam.
