### ISSUE TITLE
 Pamięć alarmu niskiej temperatury po resecie

### ISSUE THREAD

**Issue by Mirek3012** [uzi18/sterownik#96]

**Comment by uzi18** [comment]
v0.1.0.130.15
        - max czas dla podtrzymania to 240min.
        - zapamietujemy stan dla alarmu tmin po resecie
        - Dallas: alarm gdy brak czujnika lub bledy komunikacji
        - nowy alarm uszkodzonego czujnika
        - Dallas: wykrywamy sytuacje braku czujnika/czujnikow
